#!/bin/bash
# CortexOS Server — Quick Docker Install
#
# One-liner:
#   curl -sSL https://raw.githubusercontent.com/ivanuser/cortex-server-os/main/scripts/docker-install.sh | bash
#
# With API key:
#   ANTHROPIC_API_KEY=sk-ant-... bash <(curl -sSL https://raw.githubusercontent.com/ivanuser/cortex-server-os/main/scripts/docker-install.sh)
#
# With local Ollama:
#   ENABLE_OLLAMA=1 ANTHROPIC_API_KEY=sk-ant-... bash <(curl -sSL ...)

set -euo pipefail

# ─── Config ──────────────────────────────────────────────────
CORTEX_DIR="${CORTEX_DIR:-$HOME/cortexos}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
GATEWAY_TOKEN="${GATEWAY_TOKEN:-auto}"
ENABLE_OLLAMA="${ENABLE_OLLAMA:-0}"
REPO_URL="https://github.com/ivanuser/cortex-server-os.git"

# ─── Colors ──────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ─── Banner ──────────────────────────────────────────────────
echo -e "${PURPLE}"
echo "╔══════════════════════════════════════════════════════╗"
echo "║           CortexOS Server — Docker Install           ║"
echo "║         AI-Powered Server Management                 ║"
echo "╚══════════════════════════════════════════════════════╝"
echo -e "${NC}"

# ─── Pre-flight checks ──────────────────────────────────────
info "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
    error "Docker is not installed. Install it first: https://docs.docker.com/engine/install/"
fi

if ! docker compose version &>/dev/null && ! docker-compose version &>/dev/null; then
    error "Docker Compose is not available. Install Docker Compose v2: https://docs.docker.com/compose/install/"
fi

# Prefer 'docker compose' over 'docker-compose'
if docker compose version &>/dev/null; then
    COMPOSE="docker compose"
else
    COMPOSE="docker-compose"
fi

ok "Docker and Docker Compose found"

# ─── API key check ───────────────────────────────────────────
if [ -z "$ANTHROPIC_API_KEY" ] && [ -z "$OPENAI_API_KEY" ]; then
    warn "No API key provided. You'll need to set one for AI features to work."
    echo ""
    echo -e "  Set one before running this script:"
    echo -e "    ${CYAN}ANTHROPIC_API_KEY=sk-ant-... bash <(curl -sSL ...)${NC}"
    echo ""
    read -rp "Continue anyway? [y/N] " reply
    if [[ ! "$reply" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
fi

# ─── Clone or update repo ───────────────────────────────────
if [ -d "$CORTEX_DIR" ]; then
    info "Updating existing installation at $CORTEX_DIR..."
    cd "$CORTEX_DIR"
    git pull --ff-only 2>/dev/null || warn "Could not pull updates (not a git repo or conflicts)"
else
    info "Cloning CortexOS Server to $CORTEX_DIR..."
    git clone "$REPO_URL" "$CORTEX_DIR"
    cd "$CORTEX_DIR"
fi

ok "Source ready at $CORTEX_DIR"

# ─── Create .env file ───────────────────────────────────────
info "Creating environment configuration..."
cat > "$CORTEX_DIR/.env" <<EOF
# CortexOS Server Configuration
# Generated by docker-install.sh on $(date -u +"%Y-%m-%d %H:%M UTC")

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}
GATEWAY_TOKEN=${GATEWAY_TOKEN}
EOF

chmod 600 "$CORTEX_DIR/.env"
ok "Environment file created (.env)"

# ─── Build and start ────────────────────────────────────────
info "Building CortexOS Server Docker image..."
$COMPOSE build

PROFILE_FLAG=""
if [ "$ENABLE_OLLAMA" = "1" ]; then
    info "Ollama sidecar enabled"
    PROFILE_FLAG="--profile local-ai"
fi

info "Starting CortexOS Server..."
$COMPOSE $PROFILE_FLAG up -d

# ─── Wait for healthy ───────────────────────────────────────
info "Waiting for gateway to become healthy..."
for i in $(seq 1 30); do
    if curl -sf http://localhost:18789/health &>/dev/null; then
        ok "Gateway is healthy!"
        break
    fi
    if [ "$i" -eq 30 ]; then
        warn "Gateway didn't become healthy within 30s. Check logs: $COMPOSE logs cortexos"
    fi
    sleep 1
done

# ─── Done ────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║          CortexOS Server is running! 🚀              ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${CYAN}Gateway:${NC}     http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost'):18789"
if [ "$ENABLE_OLLAMA" = "1" ]; then
echo -e "  ${CYAN}Ollama:${NC}      http://localhost:11434"
fi
echo ""
echo -e "  ${CYAN}Logs:${NC}        cd $CORTEX_DIR && $COMPOSE logs -f"
echo -e "  ${CYAN}Stop:${NC}        cd $CORTEX_DIR && $COMPOSE down"
echo -e "  ${CYAN}Restart:${NC}     cd $CORTEX_DIR && $COMPOSE restart"
echo ""
if [ -z "$ANTHROPIC_API_KEY" ] && [ -z "$OPENAI_API_KEY" ]; then
    echo -e "  ${YELLOW}⚠ Remember to set your API key in $CORTEX_DIR/.env${NC}"
    echo -e "  ${YELLOW}  Then restart: cd $CORTEX_DIR && $COMPOSE restart${NC}"
    echo ""
fi
